
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Image noob;
	
	private global::Gtk.Image master;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label MasterAppTitle;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	
	private global::Gtk.TextView masterInvColorLog;
	
	private global::Gtk.Button doMasterInvColor;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Label NoobAppTitle;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.TextView noobInvColorLog;
	
	private global::Gtk.Button doNoobInvColor;
	
	private global::Gtk.FileChooserWidget selectOpenImage;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("BitMap ReverseColor\n");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-select-color", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.noob = new global::Gtk.Image ();
		this.noob.Name = "noob";
		this.noob.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Dialog);
		this.vbox1.Add (this.noob);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.noob]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.master = new global::Gtk.Image ();
		this.master.Name = "master";
		this.master.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Dialog);
		this.vbox1.Add (this.master);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.master]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.WidthRequest = 332;
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.MasterAppTitle = new global::Gtk.Label ();
		global::Gtk.Tooltips w4 = new Gtk.Tooltips ();
		w4.SetTip (this.MasterAppTitle, "Master approach", "Master approach");
		this.MasterAppTitle.Name = "MasterAppTitle";
		this.MasterAppTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Master approach");
		this.vbox3.Add (this.MasterAppTitle);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.MasterAppTitle]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.masterInvColorLog = new global::Gtk.TextView ();
		this.masterInvColorLog.CanFocus = true;
		this.masterInvColorLog.Name = "masterInvColorLog";
		this.GtkScrolledWindow3.Add (this.masterInvColorLog);
		this.vbox3.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow3]));
		w7.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.doMasterInvColor = new global::Gtk.Button ();
		this.doMasterInvColor.CanFocus = true;
		this.doMasterInvColor.Name = "doMasterInvColor";
		this.doMasterInvColor.UseUnderline = true;
		this.doMasterInvColor.Label = global::Mono.Unix.Catalog.GetString ("Full Power");
		this.vbox3.Add (this.doMasterInvColor);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.doMasterInvColor]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
		w9.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.NoobAppTitle = new global::Gtk.Label ();
		w4.SetTip (this.NoobAppTitle, "Noob Approch", "Noob Approch");
		this.NoobAppTitle.Name = "NoobAppTitle";
		this.NoobAppTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Noob approach");
		this.vbox4.Add (this.NoobAppTitle);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.NoobAppTitle]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.noobInvColorLog = new global::Gtk.TextView ();
		this.noobInvColorLog.CanFocus = true;
		this.noobInvColorLog.Name = "noobInvColorLog";
		this.GtkScrolledWindow2.Add (this.noobInvColorLog);
		this.vbox4.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow2]));
		w12.Position = 1;
		// Container child vbox4.Gtk.Box+BoxChild
		this.doNoobInvColor = new global::Gtk.Button ();
		this.doNoobInvColor.CanFocus = true;
		this.doNoobInvColor.Name = "doNoobInvColor";
		this.doNoobInvColor.UseUnderline = true;
		this.doNoobInvColor.Label = global::Mono.Unix.Catalog.GetString ("Weak Power");
		this.vbox4.Add (this.doNoobInvColor);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.doNoobInvColor]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
		w14.Position = 1;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.selectOpenImage = new global::Gtk.FileChooserWidget (((global::Gtk.FileChooserAction)(0)));
		this.selectOpenImage.Name = "selectOpenImage";
		this.hbox1.Add (this.selectOpenImage);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.selectOpenImage]));
		w16.Position = 2;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 782;
		this.DefaultHeight = 644;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
